***Limpieza y Normalización de la Data***

**Buscamos:**

- Outliers
- Nulos
- Faltantes

***LIMPIEZA DEL DATA_TEST***

In [1]:
import pandas as pd

In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
# leemos con pandas el excel para trabajar la data como dataframe y así limpiarla y normalizarla
data_test = pd.read_excel(r'C:\Users\aalbe\OneDrive\Escritorio\Datathon/E-Commerce_test.xlsx')

In [4]:
# visualizamos la data
data_test

ID Warehouse_block Mode_of_Shipment  Customer_care_calls  \
0      9000               F             Ship                    5   
1      9001               D             Ship                    5   
2      9002               F             Ship                    3   
3      9003               A             Ship                    5   
4      9004               B             Ship                    4   
...     ...             ...              ...                  ...   
1995  10995               A             Ship                    4   
1996  10996               B             Ship                    4   
1997  10997               C             Ship                    5   
1998  10998               F             Ship                    5   
1999  10999               D             Ship                    2   

      Customer_rating  Cost_of_the_Product  Prior_purchases  \
0                   1                  189                2   
1                   3                  150                2   
2                   3                  200                3   
3                   1                  133                2   
4                   2                  260                3   
...               ...                  ...              ...   
1995                1                  252                5   
1996                1                  232                5   
1997                4                  242                5   
1998                2                  223                6   
1999                5                  155                5   

     Product_importance Gender  Discount_offered  Weight_in_gms  
0                medium      M                10           5248  
1                  high      F                 9           4446  
2                   low      M                 3           5739  
3                medium      M                 1           4643  
4                   low      M                 4           5504  
...                 ...    ...               ...            ...  
1995             medium      F                 1           1538  
1996             medium      F                 6           1247  
1997                low      F                 4           1155  
1998             medium      M                 2           1210  
1999                low      F                 6           1639  

[2000 rows x 11 columns]

In [5]:
# observamos que no hay valores nulos a lo largo del dataframe
data_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype 
---  ------               --------------  ----- 
 0   ID                   2000 non-null   int64 
 1   Warehouse_block      2000 non-null   object
 2   Mode_of_Shipment     2000 non-null   object
 3   Customer_care_calls  2000 non-null   int64 
 4   Customer_rating      2000 non-null   int64 
 5   Cost_of_the_Product  2000 non-null   int64 
 6   Prior_purchases      2000 non-null   int64 
 7   Product_importance   2000 non-null   object
 8   Gender               2000 non-null   object
 9   Discount_offered     2000 non-null   int64 
 10  Weight_in_gms        2000 non-null   int64 
dtypes: int64(7), object(4)
memory usage: 172.0+ KB


In [6]:
# obtenemos más información sobre las series que contengan tipos de dato int
data_test.describe()

ID  Customer_care_calls  Customer_rating  \
count   2000.000000          2000.000000       2000.00000   
mean    9999.500000             4.231500          2.97050   
std      577.494589             1.136465          1.41585   
min     9000.000000             2.000000          1.00000   
25%     9499.750000             3.000000          2.00000   
50%     9999.500000             4.000000          3.00000   
75%    10499.250000             5.000000          4.00000   
max    10999.000000             7.000000          5.00000   

       Cost_of_the_Product  Prior_purchases  Discount_offered  Weight_in_gms  
count          2000.000000       2000.00000        2000.00000     2000.00000  
mean            217.555000          3.82000           5.61400     3857.42650  
std              46.336276          1.45453           2.90469     1707.78448  
min              96.000000          2.00000           1.00000     1003.00000  
25%             179.750000          3.00000           3.00000     1773.75000  
50%             226.000000          4.00000           6.00000     4536.00000  
75%             255.000000          5.00000           8.00000     5241.25000  
max             310.000000         10.00000          10.00000     6000.00000

In [7]:
# observamos los tipos de warehouse block nos vamos a encontrar a lo largo del dataset
data_test['Warehouse_block'].unique()

array(['F', 'D', 'A', 'B', 'C'], dtype=object)

In [8]:
data_test['Mode_of_Shipment'].unique()

array(['Ship', 'Road', 'Flight'], dtype=object)

In [9]:
data_test['Product_importance'].unique()

array(['medium', 'high', 'low'], dtype=object)

***LIMPIEZA DEL DATA_TRAIN***

In [10]:
coefs = []

In [11]:
data_train = pd.read_excel(r'C:\Users\aalbe\OneDrive\Escritorio\Datathon/E-Commerce_train.xlsx')

In [12]:
data_train

ID Warehouse_block Mode_of_Shipment  Customer_care_calls  \
0        1               D           Flight                    4   
1        2               F           Flight                    4   
2        3               A           Flight                    2   
3        4               B           Flight                    3   
4        5               C           Flight                    2   
...    ...             ...              ...                  ...   
8994  8995               D             Ship                    3   
8995  8996               F             Ship                    5   
8996  8997               A             Ship                    4   
8997  8998               B             Ship                    4   
8998  8999               C             Ship                    5   

      Customer_rating  Cost_of_the_Product  Prior_purchases  \
0                   2                  177                3   
1                   5                  216                2   
2                   2                  183                4   
3                   3                  176                4   
4                   2                  184                3   
...               ...                  ...              ...   
8994                1                  217                3   
8995                3                  232                3   
8996                5                  260                3   
8997                2                  184                3   
8998                4                  145                4   

     Product_importance Gender  Discount_offered  Weight_in_gms  \
0                   low      F                44           1233   
1                   low      M                59           3088   
2                   low      M                48           3374   
3                medium      M                10           1177   
4                medium      F                46           2484   
...                 ...    ...               ...            ...   
8994                low      F                 1           4177   
8995             medium      M                 3           4526   
8996             medium      F                 6           4221   
8997             medium      F                 5           5931   
8998                low      M                 4           4790   

      Reached.on.Time_Y.N  
0                       1  
1                       1  
2                       1  
3                       1  
4                       1  
...                   ...  
8994                    1  
8995                    0  
8996                    0  
8997                    1  
8998                    0  

[8999 rows x 12 columns]

In [13]:
# observamos que tampoco tenemos valores faltantes en el dataset de train
data_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8999 entries, 0 to 8998
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype 
---  ------               --------------  ----- 
 0   ID                   8999 non-null   int64 
 1   Warehouse_block      8999 non-null   object
 2   Mode_of_Shipment     8999 non-null   object
 3   Customer_care_calls  8999 non-null   int64 
 4   Customer_rating      8999 non-null   int64 
 5   Cost_of_the_Product  8999 non-null   int64 
 6   Prior_purchases      8999 non-null   int64 
 7   Product_importance   8999 non-null   object
 8   Gender               8999 non-null   object
 9   Discount_offered     8999 non-null   int64 
 10  Weight_in_gms        8999 non-null   int64 
 11  Reached.on.Time_Y.N  8999 non-null   int64 
dtypes: int64(8), object(4)
memory usage: 843.8+ KB


In [14]:
data_train.describe()

ID  Customer_care_calls  Customer_rating  Cost_of_the_Product  \
count  8999.00000          8999.000000      8999.000000          8999.000000   
mean   4500.00000             4.015113         2.994999           208.561507   
std    2597.93187             1.138934         1.413143            48.289172   
min       1.00000             2.000000         1.000000            96.000000   
25%    2250.50000             3.000000         2.000000           168.000000   
50%    4500.00000             4.000000         3.000000           211.000000   
75%    6749.50000             5.000000         4.000000           249.500000   
max    8999.00000             7.000000         5.000000           310.000000   

       Prior_purchases  Discount_offered  Weight_in_gms  Reached.on.Time_Y.N  
count      8999.000000       8999.000000    8999.000000          8999.000000  
mean          3.511501         15.097678    3584.364596             0.635515  
std           1.532074         17.400040    1614.750194             0.481312  
min           2.000000          1.000000    1001.000000             0.000000  
25%           3.000000          4.000000    1857.000000             0.000000  
50%           3.000000          8.000000    4046.000000             1.000000  
75%           4.000000         19.000000    4999.500000             1.000000  
max          10.000000         65.000000    7846.000000             1.000000

In [15]:
# debemos agarrar cada serie (columna del dataframe) y pasarla a array, y esos son los arrays que voy a graficar buscando alguna
# relación entre ambas variables
# una de las series que sí o sí deberá aparecer será la de si llegó en horario o no (cosa que aparece sólo en el dataset de train)
# o sea el y de nuestro modelo será ese, mientras que el x serán las demás columnas, buscando justamente una relación entre 
# una y otra

# se realizará una estudio de correlación lineal con el índice de Pearson con el objetivo de hallar correlación para 
# posteriormente crear un modelo de regresión lineal
# una vez que encontremos una x que se correlacione correcta y altamente con y, vamos a entrenar el modelo de predicción

**y = 'Reached.on.Time_Y.N'**

In [16]:
# pasamos la columna de si llegó a tiempo o no a un array de numpy con la intención de que pueda usarse dentro del modelo de 
# regresión lineal
y = data_train['Reached.on.Time_Y.N'].to_numpy()

In [17]:
y

array([1, 1, 1, ..., 0, 1, 0], dtype=int64)

In [18]:
type(y)

numpy.ndarray

**x = 'Mode_of_shipment'**

In [19]:
# para nuestra primer x, vamos a probar la correlación con 'Mode_of_shipment'
x_mode_of_shipment = data_train['Mode_of_Shipment'].to_numpy()

In [20]:
x_mode_of_shipment

array(['Flight', 'Flight', 'Flight', ..., 'Ship', 'Ship', 'Ship'],
      dtype=object)

In [22]:
# definidos x e y, vamos a estudiar la covarianza que existe entre ellas
np.cov(x_mode_of_shipment,y)
# para medir esta covarianza hay que darle un número a cada palabra porque no soporta el formato str. La covarianza debe realizarse 
# entre dos int

TypeError: unsupported operand type(s) for /: 'str' and 'int'

In [23]:
x_mode_of_shipment_list = x_mode_of_shipment.tolist()

In [24]:
x_mode_of_shipment_list

['Flight',
 'Flight',
 'Flight',
 'Flight',
 'Flight',
 'Flight',
 'Flight',
 'Flight',
 'Flight',
 'Flight',
 'Flight',
 'Flight',
 'Flight',
 'Flight',
 'Flight',
 'Flight',
 'Flight',
 'Ship',
 'Ship',
 'Ship',
 'Ship',
 'Ship',
 'Ship',
 'Ship',
 'Ship',
 'Ship',
 'Ship',
 'Ship',
 'Ship',
 'Ship',
 'Ship',
 'Ship',
 'Ship',
 'Ship',
 'Ship',
 'Ship',
 'Ship',
 'Ship',
 'Ship',
 'Ship',
 'Ship',
 'Ship',
 'Ship',
 'Ship',
 'Ship',
 'Ship',
 'Ship',
 'Ship',
 'Ship',
 'Ship',
 'Ship',
 'Ship',
 'Ship',
 'Ship',
 'Ship',
 'Ship',
 'Ship',
 'Ship',
 'Ship',
 'Ship',
 'Ship',
 'Ship',
 'Ship',
 'Ship',
 'Ship',
 'Ship',
 'Ship',
 'Ship',
 'Ship',
 'Ship',
 'Ship',
 'Ship',
 'Ship',
 'Ship',
 'Ship',
 'Ship',
 'Ship',
 'Ship',
 'Ship',
 'Ship',
 'Ship',
 'Ship',
 'Ship',
 'Ship',
 'Ship',
 'Ship',
 'Ship',
 'Ship',
 'Ship',
 'Ship',
 'Ship',
 'Ship',
 'Ship',
 'Ship',
 'Ship',
 'Ship',
 'Ship',
 'Ship',
 'Ship',
 'Ship',
 'Ship',
 'Ship',
 'Ship',
 'Ship',
 'Ship',
 'Ship',
 'Ship',
 'S

In [25]:
for index, value in enumerate(x_mode_of_shipment_list):
    if value == 'Flight':
      x_mode_of_shipment_list[index] = 0
    elif value == 'Ship':
      x_mode_of_shipment_list[index] = 1
    else:
      x_mode_of_shipment_list[index] = 2

In [26]:
x_mode_of_shipment_list

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,


In [27]:
np.cov(x_mode_of_shipment_list,y)

array([[ 0.31973415, -0.00446724],
       [-0.00446724,  0.23166141]])

In [28]:
np.corrcoef(x_mode_of_shipment_list,y)
coefs.append(np.corrcoef(x_mode_of_shipment_list,y)[0][1])

**x = Warehouse_block**

In [29]:
data_train['Warehouse_block'].unique()

array(['D', 'F', 'A', 'B', 'C'], dtype=object)

In [30]:
x_warehouse_block = data_train['Warehouse_block'].to_numpy()

In [31]:
x_warehouse_block_list = x_warehouse_block.tolist()
for index, value in enumerate(x_warehouse_block_list):
    if value == 'A':
      x_warehouse_block_list[index] = 0
    elif value == 'B':
      x_warehouse_block_list[index] = 1
    elif value == 'C':
      x_warehouse_block_list[index] = 2
    elif value == 'D':
      x_warehouse_block_list[index] = 3            
    else:
      x_warehouse_block_list[index] = 4

In [32]:
np.cov(x_warehouse_block_list,y)

array([[2.22240741e+00, 2.19224921e-03],
       [2.19224921e-03, 2.31661412e-01]])

In [33]:
np.corrcoef(x_warehouse_block_list,y)
coefs.append(np.corrcoef(x_warehouse_block_list,y)[0][1])

**x = Product_importance**

In [34]:
data_train['Product_importance'].unique()

array(['low', 'medium', 'high'], dtype=object)

In [35]:
x_product_importance = data_train['Product_importance'].to_numpy()
x_product_importance_list = x_product_importance.tolist()
for index, value in enumerate(x_product_importance_list):
    if value == 'low':
      x_product_importance_list[index] = 0
    elif value == 'medium':
      x_product_importance_list[index] = 1            
    else:
      x_product_importance_list[index] = 2

In [36]:
np.cov(x_product_importance_list,y)

array([[0.42221769, 0.00449153],
       [0.00449153, 0.23166141]])

In [37]:
np.corrcoef(x_product_importance_list,y)
coefs.append(np.corrcoef(x_product_importance_list,y)[0][1])

**x = Gender**

In [38]:
data_train['Gender'].unique()

array(['F', 'M'], dtype=object)

In [39]:
x_gender = data_train['Gender'].to_numpy()
x_gender_list = x_gender.tolist()
for index, value in enumerate(x_gender_list):
    if value == 'F':
      x_gender_list[index] = 0           
    else:
      x_gender_list[index] = 1

In [40]:
np.cov(x_gender_list,y)

array([[0.25000753, 0.00069331],
       [0.00069331, 0.23166141]])

In [41]:
np.corrcoef(x_gender_list,y)
coefs.append(np.corrcoef(x_gender_list,y)[0][1])

**x = 'Weight_in_gms'**

In [42]:
x_weight_in_gms = data_train['Weight_in_gms'].to_numpy()

In [43]:
# covarianza entre si llegó o no a tiempo, y la columna 'Weigth_in_gms'
np.cov(x_weight_in_gms,y)

array([[ 2.60741819e+06, -2.54048803e+02],
       [-2.54048803e+02,  2.31661412e-01]])

In [44]:
# correlación de pearson entre y y 'Weigth_in_gms'
np.corrcoef(x_weight_in_gms,y)

# tienen una asociación mediana

coefs.append(np.corrcoef(x_weight_in_gms,y)[0][1])

**x = Customer_care_calls**

In [45]:
x_customes_care_calls = data_train['Customer_care_calls'].to_numpy()
np.cov(x_customes_care_calls,y)

array([[ 1.297171  , -0.03961214],
       [-0.03961214,  0.23166141]])

In [46]:
np.corrcoef(x_customes_care_calls,y)
# correlación baja? D:
coefs.append(np.corrcoef(x_customes_care_calls,y)[0][1])

**x = Customer_rating**

In [47]:
x_customer_rating = data_train['Customer_rating'].to_numpy()
np.cov(x_customer_rating,y)

array([[1.99697432, 0.00751258],
       [0.00751258, 0.23166141]])

In [48]:
np.corrcoef(x_customer_rating,y)
# correlación baja? D:
coefs.append(np.corrcoef(x_customer_rating,y)[0][1])

**x = Cost_of_the_Product**

In [49]:
x_cost_of_the_product = data_train['Cost_of_the_Product'].to_numpy()
np.cov(x_cost_of_the_product,y)

array([[ 2.33184415e+03, -1.94001529e+00],
       [-1.94001529e+00,  2.31661412e-01]])

In [50]:
np.corrcoef(x_cost_of_the_product,y)
# correlación baja? 
coefs.append(np.corrcoef(x_cost_of_the_product,y)[0][1])

**x = Discount_offered**

In [51]:
x_discount_offered = data_train['Discount_offered'].to_numpy()
np.cov(x_discount_offered,y)

array([[3.02761407e+02, 3.48692846e+00],
       [3.48692846e+00, 2.31661412e-01]])

In [52]:
np.corrcoef(x_discount_offered,y)
# correlación media
coefs.append(np.corrcoef(x_discount_offered,y)[0][1])

**x = Prior_purchases**

In [53]:
x_prior_purchases = data_train['Prior_purchases'].to_numpy()
np.cov(x_prior_purchases,y)

array([[ 2.34725046, -0.03559411],
       [-0.03559411,  0.23166141]])

In [54]:
np.corrcoef(x_prior_purchases,y)
# correlación baja

coefs.append(np.corrcoef(x_prior_purchases,y)[0][1])

In [55]:
xs = ['Mode_of_shipment', 'Warehouse_block', 'Product_importance', 'Gender', 'Weight_in_gms', 'Customer_care_calls', 'Customer_rating', 'Cost_of_the_product', 'Discount_offered', 'Prior_purchases']

In [56]:
cuadro_correlaciones = pd.DataFrame()
cuadro_correlaciones['Variable'] = xs
cuadro_correlaciones['Correlación'] = coefs

In [57]:
# creamos un cuadro donde podemos observar todas las variables del dataframe que se brinda, y la debida correlación lineal de Pearson
# respecto de si el pedido llegó o no tiempo
cuadro_correlaciones
# se puede observar que las variables que más correlación tienen son: Weight_in_gms y Discount_offered

Variable  Correlación
0     Mode_of_shipment    -0.016414
1      Warehouse_block     0.003055
2   Product_importance     0.014361
3               Gender     0.002881
4        Weight_in_gms    -0.326877
5  Customer_care_calls    -0.072261
6      Customer_rating     0.011045
7  Cost_of_the_product    -0.083470
8     Discount_offered     0.416357
9      Prior_purchases    -0.048269

In [59]:
X = data_train[['ID', 'Discount_offered', 'Weight_in_gms', 'Cost_of_the_Product']]
y = data_train['Reached.on.Time_Y.N']

In [60]:
from sklearn.linear_model import LinearRegression # Importamos el módulo que contiene el algorimto de regresión lineal

modelo_regresion_lineal = LinearRegression() # Instanciamos un objeto de la clase LinearRegression. 
                                  #Aquí estamos creando nuestro modelo predictivo 'model'

modelo_regresion_lineal.fit(X,y)

LinearRegression()

In [61]:
y_pred = modelo_regresion_lineal.predict(X)

In [65]:
y_pred
# estamos frente a un problema de clasificación

array([1.12371402, 1.10989722, 1.0468644 , ..., 0.31524236, 0.23660892,
       0.28370197])